# Generated by Django 4.1 on 2022-10-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_is_active_customuser_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'СуперАдмин'), ('admin', 'Админ'), ('manager', 'Менеджер'), ('default', 'Обычный')], default='default', max_length=100, verbose_name='Role'),
        ),
    ]
