# Generated by Django 4.1 on 2022-10-04 15:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='utils.base_model.uid')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='utils.tracker_model.created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='utils.tracker_model.updated_at')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='Size')),
            ],
            options={
                'verbose_name': 'Memory',
                'verbose_name_plural': 'Memories',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='utils.base_model.uid')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='utils.tracker_model.created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='utils.tracker_model.updated_at')),
                ('company', models.CharField(choices=[('apple', 'Apple'), ('samsung', 'Samsung'), ('xiaomi', 'Xiaomi'), ('blackberry', 'Blackberry'), ('other', 'Other')], default='other', max_length=255, verbose_name='Company')),
                ('model', models.CharField(max_length=255, verbose_name='Model')),
                ('color', models.CharField(choices=[('white', 'White'), ('black', 'Black'), ('blue', 'Blue'), ('red', 'Red'), ('no_color', 'No Color')], default='no_color', max_length=255, verbose_name='Color')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Price')),
                ('description', models.CharField(max_length=1000, verbose_name='Description')),
                ('memory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phones', to='products.memory', verbose_name='Memory')),
            ],
            options={
                'verbose_name': 'Phone',
                'verbose_name_plural': 'Phones',
            },
        ),
    ]
